-- 코드를 입력하세요
-- 아래 두 코드 모두 가능하다.
-- TLNO IS NOT NULL로 TLNO가 NULL이 아닌경우에만 출력할 수 있도록 지정할 수 있고 DATE_FORMAT으로 DATE 형식을 지정해주었다.

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER='W' AND DATE_OF_BIRTH LIKE '%03%' AND IFNULL(TLNO,FALSE)
ORDER BY MEMBER_ID ASC

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER='W' AND DATE_OF_BIRTH LIKE '%03%' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC