SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE A JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID IN (
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID)=
(SELECT MAX(CNT.C)
FROM(
SELECT MEMBER_ID, COUNT(MEMBER_ID) AS C
FROM REST_REVIEW
GROUP BY MEMBER_ID) CNT))
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
# 리뷰개수 가장 많은 사람 아이디 찾기
# 그 아이디와 일치하는 리뷰내용 찾기