-- 코드를 입력하세요
WITH SIGNUP_USER AS(
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE "2021-%"
)

SELECT DATE_FORMAT(SALES_DATE,"%Y") AS YEAR
,DATE_FORMAT(SALES_DATE,"%m") AS MONTH
,COUNT(DISTINCT USER_ID) AS PUCHASED_USERS
,ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*) FROM SIGNUP_USER),1) AS PUCHASED_RATIO
FROM SIGNUP_USER INNER JOIN ONLINE_SALE USING(USER_ID)
GROUP BY YEAR,MONTH
ORDER BY YEAR ASC, MONTH ASC