SELECT CAR_ID, A.CAR_TYPE, ROUND(((DAILY_FEE-(DAILY_FEE*DISCOUNT_RATE/100))*30)) AS FEE
FROM
CAR_RENTAL_COMPANY_CAR A JOIN
(SELECT CAR_TYPE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = "30일 이상" AND CAR_TYPE IN ("세단", "SUV")) B
ON A.CAR_TYPE=B.CAR_TYPE
WHERE CAR_ID NOT IN(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE END_DATE > "2022-11-01"
)
AND ROUND(((DAILY_FEE-(DAILY_FEE*DISCOUNT_RATE/100))*30)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE ASC, CAR_ID DESC